[versions]

# Minecraft
minecraft = "26.3-rc-2"
neoform = "26.3-rc-2-1"
fabric-api = "0.160.4+26.3"
neoforge = "26.3.0.0-beta"

# Libraries
modmenu = "21.0.0-beta.1"
resourceful-service-plugin = "1.0.0"

# Plugins
resourceful-minecraft = "2.0.0"

[libraries]

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }

service-plugin = { module = "com.teamresourceful:resourceful-service-plugin", version.ref = "resourceful-service-plugin" }

[plugins]

resourceful-minecraft = { id = "com.teamresourceful.plugins.minecraft", version.ref = "resourceful-minecraft" }
resourceful-gradle = { id = "com.teamresourceful.resourcefulgradle" }